### ISSUE TITLE
Funding info on Home Page

### ISSUE THREAD

**Issue by kjcoulter** [mosdef-hub/mosdef-hub.github.io#13]
Home page (June 16, 2020) lists 3 grant numbers, but there are 8.  Each institution is separately funded.  Perhaps the grant numbers for each could be listed under their logo and the overarching statement could be:

MoSDeF is supported by a Cyberinfrastructure for Sustained Scientific Innovation (CSSI) grant funded by the National Science Foundation Office of Advanced Cyberinfrastructure.

The grant numbers are:
1835613 Arthi . Jayaraman, University of Delaware
1835630 Edward J. Maginn, University of Notre Dame
1835593 Eric . Jankowski, Boise State University
1835713 Jeffrey J. Potoff, Wayne State University
1835560 Jeremy . Palmer, University of Houston
1835612 Sharon C. Glotzer, University of Michigan
1835067 Joern Ilja . Siepmann, University of Minnesota-Twin Cities
1835874 Peter T. Cummings, Vanderbilt University

**Comment by umesh-timalsina** [comment]
Sure, this can be changed relatively easily.

**Comment by umesh-timalsina** [comment]
Fixed in #14.
