### ISSUE TITLE
Change the homepage language

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/mosdef-hub.github.io#16]
Wondering if the language on the MoSDeF homepage should be modified, since MoSDeF supports more than just molecular dynamics simulations.

```
MoSDeF presents a set of extensible Python tools designed to facilitate the initialization, atom-typing, and screening of soft matter systems using molecular dynamics simulations
```

**Comment by mikemhenry** [comment]
This is what peter had:
`MoSDeF presents a set of extensible Python tools designed to facilitate the initialization, atom-typing, and screening of soft matter systems using molecular simulation.`
I'm wondering if "soft matter" needs to be changed as well or if we all fit underneath that umbrella.
